# Generated by Django 4.2.3 on 2023-11-06 19:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election', models.IntegerField(choices=[(544, 'Eleição Federal - 2022 (1 turno)'), (546, 'Eleição Estadual - 2022 (1 turno)'), (545, 'Eleição Federal - 2022 (2 turno)'), (547, 'Eleição Estadual - 2022 (2 turno)'), (9579, 'Teste 1')])),
                ('local', models.CharField(max_length=200, verbose_name='Local')),
                ('position', models.CharField(max_length=100, verbose_name='Cargo')),
                ('value', models.JSONField(verbose_name='Candidatos')),
            ],
        ),
        migrations.CreateModel(
            name='Mun',
            fields=[
                ('state', models.CharField(max_length=5, verbose_name='Estado')),
                ('code', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(99999)], verbose_name='Código')),
                ('code_i', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99999)], verbose_name='Código IBGE')),
                ('name', models.CharField(max_length=300, verbose_name='Nome Município')),
                ('is_capital', models.BooleanField(verbose_name='Capital')),
                ('zones', models.JSONField(verbose_name='Zonas Eleitorais')),
            ],
        ),
        migrations.CreateModel(
            name='StateData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election', models.IntegerField(choices=[(544, 'Eleição Federal - 2022 (1 turno)'), (546, 'Eleição Estadual - 2022 (1 turno)'), (545, 'Eleição Federal - 2022 (2 turno)'), (547, 'Eleição Estadual - 2022 (2 turno)'), (9579, 'Teste 1')])),
                ('code', models.CharField(max_length=3, verbose_name='Código')),
                ('value', models.JSONField(blank=True, default=dict, null=True, verbose_name='Resultados')),
                ('brief', models.JSONField(blank=True, default=dict, null=True, verbose_name='Resumo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado')),
                ('muns', models.JSONField(blank=True, null=True, verbose_name='Municípios')),
            ],
            options={
                'abstract': False,
                'unique_together': {('election', 'code')},
            },
        ),
        migrations.CreateModel(
            name='MunData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election', models.IntegerField(choices=[(544, 'Eleição Federal - 2022 (1 turno)'), (546, 'Eleição Estadual - 2022 (1 turno)'), (545, 'Eleição Federal - 2022 (2 turno)'), (547, 'Eleição Estadual - 2022 (2 turno)'), (9579, 'Teste 1')])),
                ('code', models.CharField(max_length=3, verbose_name='Código')),
                ('value', models.JSONField(blank=True, default=dict, null=True, verbose_name='Resultados')),
                ('brief', models.JSONField(blank=True, default=dict, null=True, verbose_name='Resumo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado')),
            ],
            options={
                'abstract': False,
                'unique_together': {('election', 'code')},
            },
        ),
        migrations.CreateModel(
            name='BRData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election', models.IntegerField(choices=[(544, 'Eleição Federal - 2022 (1 turno)'), (546, 'Eleição Estadual - 2022 (1 turno)'), (545, 'Eleição Federal - 2022 (2 turno)'), (547, 'Eleição Estadual - 2022 (2 turno)'), (9579, 'Teste 1')])),
                ('code', models.CharField(max_length=3, verbose_name='Código')),
                ('value', models.JSONField(blank=True, default=dict, null=True, verbose_name='Resultados')),
                ('brief', models.JSONField(blank=True, default=dict, null=True, verbose_name='Resumo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado')),
                ('states', models.JSONField(blank=True, default=dict, null=True, verbose_name='Estados')),
                ('muns', models.JSONField(blank=True, default=dict, null=True, verbose_name='Municípios')),
            ],
            options={
                'abstract': False,
                'unique_together': {('election', 'code')},
            },
        ),
    ]
