# Generated by Django 4.2.3 on 2023-10-29 19:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Número')),
                ('year', models.IntegerField(verbose_name='Ano')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Código')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eleicoes.election')),
            ],
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99999)], verbose_name='Código')),
                ('code_i', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99999)], verbose_name='Código IBGE')),
                ('name', models.CharField(max_length=200, verbose_name='Nome Município')),
                ('is_capital', models.BooleanField(verbose_name='Capital')),
                ('zones', models.JSONField(verbose_name='Zonas Eleitorais')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eleicoes.state')),
            ],
        ),
    ]
