# Generated by Django 4.2.3 on 2023-10-29 23:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleicoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipality',
            name='code',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(99999)], verbose_name='Código'),
        ),
    ]
