# Generated by Django 4.2.3 on 2023-11-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleicoes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidates',
            name='local',
        ),
        migrations.AddField(
            model_name='candidates',
            name='code',
            field=models.CharField(default=1, max_length=200, verbose_name='Codigo Local'),
            preserve_default=False,
        ),
    ]
