# Generated by Django 4.2.3 on 2023-10-30 00:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleicoes', '0002_alter_municipality_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='municipality',
            name='id',
        ),
        migrations.AlterField(
            model_name='municipality',
            name='code',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(99999)], verbose_name='Código'),
        ),
    ]
