# Generated by Django 4.2.3 on 2023-10-30 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eleicoes', '0003_candidate_remove_municipality_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Candidate',
        ),
    ]
