# Generated by Django 4.2.3 on 2023-11-08 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleicoes', '0004_alter_brdata_code_alter_mundata_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brdata',
            old_name='code',
            new_name='cdabr',
        ),
        migrations.RenameField(
            model_name='brdata',
            old_name='election',
            new_name='ele',
        ),
        migrations.RenameField(
            model_name='candidates',
            old_name='position',
            new_name='carg',
        ),
        migrations.RenameField(
            model_name='candidates',
            old_name='code',
            new_name='cdabr',
        ),
        migrations.RenameField(
            model_name='mundata',
            old_name='code',
            new_name='cdabr',
        ),
        migrations.RenameField(
            model_name='mundata',
            old_name='election',
            new_name='ele',
        ),
        migrations.RenameField(
            model_name='statedata',
            old_name='code',
            new_name='cdabr',
        ),
        migrations.RenameField(
            model_name='statedata',
            old_name='election',
            new_name='ele',
        ),
        migrations.RemoveField(
            model_name='candidates',
            name='election',
        ),
        migrations.AddField(
            model_name='candidates',
            name='ele',
            field=models.IntegerField(choices=[(544, 'Eleição Federal - 2022 (1 turno)'), (546, 'Eleição Estadual - 2022 (1 turno)'), (545, 'Eleição Federal - 2022 (2 turno)'), (547, 'Eleição Estadual - 2022 (2 turno)'), (9579, 'Teste 1')], default=1, verbose_name='Eleição'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='brdata',
            unique_together={('ele', 'cdabr')},
        ),
        migrations.AlterUniqueTogether(
            name='mundata',
            unique_together={('ele', 'cdabr')},
        ),
        migrations.AlterUniqueTogether(
            name='statedata',
            unique_together={('ele', 'cdabr')},
        ),
    ]
