# Generated by Django 4.2.3 on 2023-10-30 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleicoes', '0004_delete_candidate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False, verbose_name='Código')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('party', models.CharField(max_length=5, verbose_name='Partido')),
                ('dvt', models.CharField(max_length=5, verbose_name='Destinação Voto')),
                ('vs', models.JSONField(verbose_name='Vice / Suplente')),
            ],
        ),
    ]
