# Generated by Django 4.2.3 on 2023-10-31 23:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eleicoes', '0005_candidate'),
    ]

    operations = [
        migrations.CreateModel(
            name='BR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('states', models.JSONField(verbose_name='Estados')),
                ('muns', models.JSONField(verbose_name='Municípios')),
                ('value', models.JSONField(verbose_name='Resultados')),
                ('updated_at', models.DateTimeField(verbose_name='Atualizado')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eleicoes.election')),
            ],
        ),
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election', models.CharField(max_length=100, verbose_name='Eleição')),
                ('cands', models.JSONField(verbose_name='Candidatos')),
                ('state', models.CharField(max_length=4, verbose_name='Estado')),
                ('position', models.CharField(max_length=100, verbose_name='Cargo')),
                ('mun', models.CharField(blank=True, max_length=10, null=True, verbose_name='Município')),
            ],
        ),
        migrations.CreateModel(
            name='Mun',
            fields=[
                ('state', models.CharField(max_length=3, verbose_name='Estado')),
                ('code', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(99999)], verbose_name='Código')),
                ('code_i', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99999)], verbose_name='Código IBGE')),
                ('name', models.CharField(max_length=200, verbose_name='Nome Município')),
                ('is_capital', models.BooleanField(verbose_name='Capital')),
                ('zones', models.JSONField(verbose_name='Zonas Eleitorais')),
            ],
        ),
        migrations.CreateModel(
            name='MunData',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(99999)], verbose_name='Código')),
                ('value', models.JSONField(verbose_name='Resultados')),
                ('updated_at', models.DateTimeField(verbose_name='Atualizado')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eleicoes.election')),
            ],
        ),
        migrations.CreateModel(
            name='StateData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Código')),
                ('muns', models.JSONField(verbose_name='Municípios')),
                ('value', models.JSONField(verbose_name='Resultados')),
                ('updated_at', models.DateTimeField(verbose_name='Atualizado')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eleicoes.election')),
            ],
        ),
        migrations.DeleteModel(
            name='Candidate',
        ),
        migrations.RemoveField(
            model_name='state',
            name='election',
        ),
        migrations.DeleteModel(
            name='Municipality',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
