# Generated by Django 4.2.3 on 2023-11-15 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eleicoes', '0005_rename_code_brdata_cdabr_rename_election_brdata_ele_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mun',
            old_name='is_capital',
            new_name='c',
        ),
        migrations.RenameField(
            model_name='mun',
            old_name='code',
            new_name='cd',
        ),
        migrations.RenameField(
            model_name='mun',
            old_name='code_i',
            new_name='cd_i',
        ),
        migrations.RenameField(
            model_name='mun',
            old_name='name',
            new_name='nm',
        ),
        migrations.RenameField(
            model_name='mun',
            old_name='state',
            new_name='uf',
        ),
        migrations.RenameField(
            model_name='mun',
            old_name='zones',
            new_name='z',
        ),
    ]
