# Generated by Django 4.2.3 on 2023-11-01 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleicoes', '0006_br_candidates_mun_mundata_statedata_delete_candidate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BRData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election', models.IntegerField(choices=[(544, 'Eleição Federal - 2022 (1 turno)'), (546, 'Eleição Estadual - 2022 (1 turno)'), (545, 'Eleição Federal - 2022 (2 turno)'), (547, 'Eleição Estadual - 2022 (2 turno)')])),
                ('states', models.JSONField(verbose_name='Estados')),
                ('muns', models.JSONField(verbose_name='Municípios')),
                ('value', models.JSONField(verbose_name='Resultados')),
                ('updated_at', models.DateTimeField(verbose_name='Atualizado')),
            ],
        ),
        migrations.AlterField(
            model_name='candidates',
            name='election',
            field=models.IntegerField(choices=[(544, 'Eleição Federal - 2022 (1 turno)'), (546, 'Eleição Estadual - 2022 (1 turno)'), (545, 'Eleição Federal - 2022 (2 turno)'), (547, 'Eleição Estadual - 2022 (2 turno)')]),
        ),
        migrations.AlterField(
            model_name='mundata',
            name='election',
            field=models.IntegerField(choices=[(544, 'Eleição Federal - 2022 (1 turno)'), (546, 'Eleição Estadual - 2022 (1 turno)'), (545, 'Eleição Federal - 2022 (2 turno)'), (547, 'Eleição Estadual - 2022 (2 turno)')]),
        ),
        migrations.AlterField(
            model_name='statedata',
            name='election',
            field=models.IntegerField(choices=[(544, 'Eleição Federal - 2022 (1 turno)'), (546, 'Eleição Estadual - 2022 (1 turno)'), (545, 'Eleição Federal - 2022 (2 turno)'), (547, 'Eleição Estadual - 2022 (2 turno)')]),
        ),
        migrations.DeleteModel(
            name='BR',
        ),
        migrations.DeleteModel(
            name='Election',
        ),
    ]
