# Generated by Django 4.2.3 on 2023-11-18 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eleicoes', '0006_rename_is_capital_mun_c_rename_code_mun_cd_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mun',
            old_name='cd_i',
            new_name='cdi',
        ),
    ]
