# Generated by Django 4.2.3 on 2023-11-18 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eleicoes', '0007_rename_cd_i_mun_cdi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brdata',
            old_name='value',
            new_name='values',
        ),
        migrations.RenameField(
            model_name='mundata',
            old_name='value',
            new_name='values',
        ),
        migrations.RenameField(
            model_name='statedata',
            old_name='value',
            new_name='values',
        ),
    ]
