# Generated by Django 4.2.3 on 2023-11-01 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleicoes', '0007_brdata_alter_candidates_election_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidates',
            name='mun',
        ),
        migrations.RemoveField(
            model_name='candidates',
            name='state',
        ),
        migrations.AddField(
            model_name='candidates',
            name='local',
            field=models.CharField(default='ZZ', max_length=200, verbose_name='Local'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brdata',
            name='election',
            field=models.IntegerField(choices=[(544, 'Eleição Federal - 2022 (1 turno)'), (546, 'Eleição Estadual - 2022 (1 turno)'), (545, 'Eleição Federal - 2022 (2 turno)'), (547, 'Eleição Estadual - 2022 (2 turno)'), (9579, 'Teste 1')]),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='election',
            field=models.IntegerField(choices=[(544, 'Eleição Federal - 2022 (1 turno)'), (546, 'Eleição Estadual - 2022 (1 turno)'), (545, 'Eleição Federal - 2022 (2 turno)'), (547, 'Eleição Estadual - 2022 (2 turno)'), (9579, 'Teste 1')]),
        ),
        migrations.AlterField(
            model_name='mundata',
            name='election',
            field=models.IntegerField(choices=[(544, 'Eleição Federal - 2022 (1 turno)'), (546, 'Eleição Estadual - 2022 (1 turno)'), (545, 'Eleição Federal - 2022 (2 turno)'), (547, 'Eleição Estadual - 2022 (2 turno)'), (9579, 'Teste 1')]),
        ),
        migrations.AlterField(
            model_name='statedata',
            name='election',
            field=models.IntegerField(choices=[(544, 'Eleição Federal - 2022 (1 turno)'), (546, 'Eleição Estadual - 2022 (1 turno)'), (545, 'Eleição Federal - 2022 (2 turno)'), (547, 'Eleição Estadual - 2022 (2 turno)'), (9579, 'Teste 1')]),
        ),
    ]
