# Generated by Django 4.2.3 on 2023-11-18 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eleicoes', '0008_rename_value_brdata_values_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidates',
            old_name='carg',
            new_name='carper',
        ),
    ]
