# Generated by Django 4.2.3 on 2023-11-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleicoes', '0010_rename_value_candidates_values'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdabr', models.CharField(max_length=200, verbose_name='Codigo Local')),
                ('arq', models.JSONField(verbose_name='Arquivos')),
            ],
        ),
    ]
