# Generated by Django 4.2.3 on 2023-11-01 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eleicoes', '0010_alter_mun_code_alter_mun_code_i_alter_mun_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidates',
            old_name='cands',
            new_name='value',
        ),
    ]
