import numpy as np
mapping_sit = {
    np.nan: 0,
    "EM FUNCIONAMENTO NORMAL": 1,
    "EM SITUAÇÃO ESPECIAL": 2,
    "LIQUIDAÇÃO": 3,
    "FASE PRÉ-OPERACIONAL": 4,
    "EM ANÁLISE": 5,
    "INCORPORAÇÃO": 6,
    "CANCELADA": 7,
}

mapping = {'S': 1, 'N': 0}

mapping_classe = {
    np.nan: 0,
    "Fundo Multimercado": 1,
    "Fundo de Ações": 2,
    "Fundo de Renda Fixa": 3,
    "Fundo Cambial": 4,
    "FIDC": 5,
    "FIDC-NP": 6,
    "FIC FIDC": 7,
    "FICFIDC-NP": 8,
    "FMP-FGTS": 9,
    "FIDCFIAGRO": 10,
    "FIP Multi": 11,
    "FIP": 12,
    "FIP CS": 13,
    "FIC FIP": 14,
    "FIP EE": 15,
    "FIP IE": 16,
    "FII": 17,
    "FII-FIAGRO": 18,
    "FIP-FIAGRO": 19,
    "FUNCINE": 20,
    "FIDC-PIPS": 21,
    "FMIEE": 22,
    "Fundo Referenciado": 23,
    "Fundo de Curto Prazo": 24,
    "Fundo da Dívida Externa": 25,
    "FIP PD&I": 26,
}

mapping_classe_anbima = {
    np.nan: 0, 
    "Renda Fixa Duração Livre Grau de Invest.": 1,
    "Renda Fixa Duração Livre Crédito Livre": 2,
    "Ações Invest. no Exterior": 3,
    "Fechados de Ações": 4,
    "Ações Livre": 5,
    "Renda Fixa Duração Baixa Crédito Livre": 6,
    "Renda Fixa Duração Média Grau de Invest.": 7,
    "Renda Fixa Duração Baixa Grau de Invest.": 8,
    "Multimercados Livre": 9,
    "Renda Fixa Dívida Externa": 10,
    "Multimercados Macro": 11,
    "Ações Índice Ativo": 12,
    "Cambial": 13,
    "Ações Valor/Crescimento": 14,
    "Renda Fixa Duração Livre Soberano": 15,
    "Renda Fixa Duração Baixa Soberano": 16,
    "Renda Fixa Duração Alta Grau de Invest.": 17,
    "Multimercados Invest. no Exterior": 18,
    "Multimercados Juros e Moedas": 19,
    "Multimercados Balanceados": 20,
    "Ações Small Caps": 21,
    "Previdência RF Duração Livre Grau de Inv": 22,
    "Ações Indexados": 23,
    "Renda Fixa Duração Média Crédito Livre": 24,
    "Previdência Balanceados de 30-49": 25,
    "Previdência RF Duração Média Grau de Inv": 26,
    "Ações Setoriais": 27,
    "Fundos de Participações": 28,
    "Ações Dividendos": 29,
    "Multimercados Estrat. Específica": 30,
    "Previdência RF Duração Livre Crédito Liv": 31,
    "Renda Fixa Indexados": 32,
    "Previdência Balanceados de 15-30": 33,
    "Previdência RF Duração Baixa Grau de Inv": 34,
    "Previdência Balanceados até 15": 35,
    "Ações FMP - FGTS": 36,
    "Previdência Multimercado Livre": 37,
    "Previdência RF Duração Alta Grau de Inv.": 38,
    "Previdência RF Duração Livre Soberano": 39,
    "Multimercados Dinâmico": 40,
    "Previdência Ações Indexados": 41,
    "Multimercados L/S - Direcional": 42,
    "Fundos de Mono Ação": 43,
    "Previdência RF Indexados": 44,
    "Ações Sustentabilidade/Governança": 45,
    "FII Hibrido Gestão Ativa": 46,
    "Multimercados Trading": 47,
    "Renda Fixa Duração Média Soberano": 48,
    "Previdência Multimercados Juros e Moedas": 49,
    "Previdência Balanceados Data Alvo": 50,
    "Previdência Ações Ativo": 51,
    "Multimercados L/S - Neutro": 52,
    "Previdência RF Duração Baixa Soberano": 53,
    "Multimercados Capital Protegido": 54,
    "Renda Fixa Duração Alta Soberano": 55,
    "Renda Fixa Duração Alta Crédito Livre": 56,
    "Previdência RF Duração Alta Soberano": 57,
    "FIDC Outros": 58,
    "FIDC Fomento Mercantil": 59,
    "Previdência RF Duração Baixa Crédito Liv": 60,
    "FII Renda Gestão Ativa": 61,
    "Previdência RF Data Alvo": 62,
    "Previdência RF Duração Média Soberano": 63,
    "Renda Fixa Invest. no Exterior": 64,
    "Previdência RF Duração Média Crédito Liv": 65,
    "Previdência Balanceados acima de 49": 66,
    "Previdência RF Duração Alta Crédito Livr": 67,
}